// Run with PLAYWRIGHT_MODULE pointing to the installed playwright package if not on NODE_PATH.
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async()=>{
  fs.mkdirSync('artifacts', {recursive:true});
  const browser = await chromium.launch({headless:true, channel:process.env.BROWSER_CHANNEL || 'chrome'});
  const page = await browser.newPage({viewport:{width:1440,height:1050}});
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://127.0.0.1:8080');
  await page.waitForSelector('#disk-table tbody tr');
  assert.equal(await page.locator('#disk-table tbody tr').count(),24);
  await page.getByRole('button',{name:'Disk',exact:false}).first().click();
  assert.equal(await page.locator('#disk-table tbody tr').first().locator('td').first().innerText(),'sdx');
  await page.locator('#disk-table a').first().focus();
  await page.evaluate(()=>refresh());
  assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('href')),'/disks/sdx');
  await page.screenshot({path:'artifacts/dashboard-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'artifacts/dashboard-mobile.png',fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth));
  await page.goto('http://127.0.0.1:8080/disks/sdc');
  await page.waitForSelector('#timeout-table tbody tr');
  assert.equal(await page.locator('#timeout-table tbody tr').count(),4);
  await page.screenshot({path:'artifacts/disk-mobile.png',fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth));
  await page.setViewportSize({width:1440,height:1050});
  await page.screenshot({path:'artifacts/disk-desktop.png',fullPage:true});
  await page.goto('http://127.0.0.1:8080/analysis');
  await page.waitForSelector('#array-table tbody tr');
  await page.screenshot({path:'artifacts/analysis-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'artifacts/analysis-mobile.png',fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth));
  await page.goto('http://127.0.0.1:8080/settings');
  await page.waitForSelector('[data-disk]');
  await page.waitForFunction(()=>!document.querySelector('#save-settings').disabled);
  await page.locator('[data-disk="sdb"]').uncheck();
  await page.evaluate(async()=>{
    const disks=await api('disks');
    updateDiskSelection(disks.map(d=>d.device_name==='sda' ? {...d,eligible:0}:d));
  });
  assert(await page.locator('[data-disk="sda"]').isDisabled());
  await page.evaluate(()=>refresh());
  assert(await page.locator('[data-disk="sda"]').isEnabled());
  assert.equal(await page.locator('[data-disk="sdb"]').isChecked(),false);
  await page.locator('[data-disk="sdb"]').check();
  await page.getByLabel('Tested delays, minutes').fill('15, 30, 60, 120, 180');
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByText('Saved. Collection changes take effect at the next sample.',{exact:true}).waitFor();
  await page.reload();
  await page.waitForFunction(()=>!document.querySelector('#save-settings').disabled);
  assert.equal(await page.getByLabel('Tested delays, minutes').inputValue(),'15, 30, 60, 120, 180');
  await page.getByLabel('Tested delays, minutes').fill('15, 30, 60, 120');
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByText('Saved. Collection changes take effect at the next sample.',{exact:true}).waitFor();
  await page.screenshot({path:'artifacts/settings-mobile.png',fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth));
  await page.setViewportSize({width:1440,height:1050});
  await page.screenshot({path:'artifacts/settings-desktop.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('Browser checks passed: 24 disks, sorting, details, array, settings persistence, 390px overflow, no JS errors.');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
